[package]
name = "mdproof"
version = "0.1.0"
authors = ["LeRoyce Pearson <leroycepearson@geemili.xyz>"]
edition = "2018"

[dependencies]
quicli = "0.3"
pulldown-cmark = "0"
printpdf = "*"
rusttype = "*"
failure = "*"
quick-xml = "*"
image = "*"
log = "*"
